"""Sonification event schema.

Defines the structured event model that bridges biological analysis
and audio rendering. Every important audio event must be traceable
to data through this schema.

The event model is serializable, deterministic, and versionable.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Optional, Any
import json
import uuid


class EventType(Enum):
    """Type of sonification event."""

    NUCLEOTIDE = "nucleotide"
    CODON = "codon"
    CHORD = "chord"
    INTERVAL = "interval"
    START_CODON = "start_codon"
    STOP_CODON = "stop_codon"
    SILENCE = "silence"


@dataclass(frozen=True)
class SonificationEvent:
    """A single event in a sonification timeline.

    This is the atomic unit of audio representation. Every event
    maps to exactly one biological position and one audio output.
    """

    # Identity
    event_id: str
    analysis_id: str
    sequence_id: str  # "reference" or "sample"

    # Biological source
    position: int  # Position in the original sequence
    frame: int  # Reading frame (0, 1, or 2)
    event_type: EventType
    biological_value: str  # e.g., "A", "ATG", "C-G-A"

    # Audio parameters
    start_time: float  # Seconds from start of timeline
    duration: float  # Seconds
    pitch: str  # Musical note name (e.g., "C4")
    frequency: float  # Hz
    amplitude: float  # 0.0 to 1.0
    instrument: str  # Timbre identifier

    # Multi-event support (for chords)
    simultaneous_pitches: tuple[SimultaneousPitch, ...] = ()
    simultaneous_frequencies: tuple[float, ...] = ()

    # Provenance
    profile: str = "paper_2017"
    source_algorithm: str = ""
    source_paper: str = "s12859-017-1632-x.pdf"
    mapping_description: str = ""

    # Scientific fidelity provenance
    # paper_rule: what the paper says (e.g., "higher pitch", "100ms duration")
    # implementation: what we actually do (e.g., "+12 semitones", "0.1s")
    # implementation_source: "PAPER_EXACT" | "PAPER_DERIVED" | "PAPER_QUALITATIVE" |
    #                        "AUDIGENE_INTERPRETATION" | "AUDIGENE_INNOVATION"
    paper_rule: str = ""
    implementation: str = ""
    implementation_source: str = ""

    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        d = asdict(self)
        d["event_type"] = self.event_type.value
        d["simultaneous_pitches"] = list(self.simultaneous_pitches)
        d["simultaneous_frequencies"] = list(self.simultaneous_frequencies)
        return d

    def to_json(self) -> str:
        """Serialize to JSON string."""
        return json.dumps(self.to_dict(), indent=2)


@dataclass(frozen=True)
class SimultaneousPitch:
    """A pitch that sounds simultaneously with the main event (for chords)."""

    pitch: str  # Musical note name
    frequency: float  # Hz
    amplitude: float  # 0.0 to 1.0


@dataclass(frozen=True)
class SonificationTimeline:
    """A complete timeline of sonification events.

    Generated by a sonification method from biological analysis.
    This is the input to the audio rendering engine.
    """

    analysis_id: str
    profile: str
    events: tuple[SonificationEvent, ...]
    total_duration: float
    sequence_length: int
    method: str  # Which sonification method generated this

    @property
    def event_count(self) -> int:
        return len(self.events)

    def events_in_range(self, start_time: float, end_time: float) -> tuple[SonificationEvent, ...]:
        """Get events within a time range."""
        return tuple(
            e for e in self.events
            if e.start_time >= start_time and e.start_time < end_time
        )

    def event_at_time(self, time: float) -> Optional[SonificationEvent]:
        """Find the event playing at a given time."""
        for e in self.events:
            if e.start_time <= time < e.start_time + e.duration:
                return e
        return None

    def position_at_time(self, time: float) -> Optional[int]:
        """Get the sequence position at a given time."""
        event = self.event_at_time(time)
        return event.position if event else None

    def to_dict(self) -> dict:
        return {
            "analysis_id": self.analysis_id,
            "profile": self.profile,
            "events": [e.to_dict() for e in self.events],
            "total_duration": self.total_duration,
            "sequence_length": self.sequence_length,
            "method": self.method,
        }


def create_event_id() -> str:
    """Generate a unique event ID."""
    return str(uuid.uuid4())[:8]


def create_analysis_id() -> str:
    """Generate a unique analysis ID."""
    return f"analysis-{str(uuid.uuid4())[:8]}"
